version: '3.5'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: pharmatech-api
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/app

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: pharmatech-pgadmin
    env_file:
      - .env
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  postgres:
  pgadmin: